<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EFCoreMastery.Domain\EFCoreMastery.Domain.csproj" />
    <ProjectReference Include="..\EFCoreMastery.Persistence\EFCoreMastery.Persistence.csproj" />
    <ProjectReference Include="..\EFCoreMastery.Services\EFCoreMastery.Services.csproj" />
  </ItemGroup>

</Project>
