<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.20" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EFCoreMastery.Domain\EFCoreMastery.Domain.csproj" />
  </ItemGroup>

</Project>
